services:
  
  backend_app_1:
    image: hashicorp/http-echo
    networks:
      - backend
  
  backend_app_2:
    image: nginx:latest
    networks:
      - backend

  client:
    image: ubuntu:latest
    networks:
      - frontend
    tty: true

  proxy:
    image: nginx:latest
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./certs:/etc/nginx/certs:ro"
      - "./nginx.conf:/etc/nginx/conf.d/nginx.conf:ro"

networks:
  backend:
  frontend: