services:
  
  backend_app_1:
    image: hashicorp/http-echo
    networks:
      - backend
#    ports:
#      - "443:5678" 
  
  backend_app_2:
    image: nginx:latest
    networks:
      - backend
  
  proxy:
    image: nginx:latest
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
      - "4343:443"
    volumes:
      - "./certs:/etc/nginx/certs:ro"
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"

networks:
  backend:
  frontend:
