user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /run/nginx.pid;

events {
    worker_connections  1024;
}

http {
	server {
	
		listen 80;
		listen [::]:80;
	
		# listen 443 ssl;
		# listen [::]:443 ssl;

		# server_name 		www.proxy-reverso.com;
	
		# ssl_certificate 	certs/cert.pem;
		# ssl_certificate_key 	certs/key.pem;
	
		# ssl_protocols		TLSv1.2 TLSv1.3;
		# ssl_ciphers		HIGH:!aNULL:!MD5;	

		# server_name backend_app_2 www.backend_app_2;

		location / {
		
			proxy_set_header Host $http_host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Proto $scheme;
		
			if ($scheme = http) {
				return 301 "Coneção http movida para https";
			}
			# proxy_pass http://localhost:80;
		}
	}
}




#http {
#    include       /etc/nginx/mime.types;
#    default_type  application/octet-stream;
#
#    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
#                      '$status $body_bytes_sent "$http_referer" '
#                      '"$http_user_agent" "$http_x_forwarded_for"';
#
#access_log  /var/log/nginx/access.log  main;

    #sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  65;

    #gzip  on;

    #include /etc/nginx/conf.d/*.conf;
    #}

