name: Push File 

on: 
  push:
    types: opened

permissions:
  pushs: write

jobs:
  Pushing-Text-Files: 
    runs-on: ubuntu-latest
    steps:
      - run: echo "Treinando integração continua."
      - run: echo "Bom dia"

